spring:
  application:
    name: nexa-spring-helloworld

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/helloworld
    username: nexaspring
    password: ${HELLOWORLD_DB_PASSWORD}
    hikari:
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080
